services:
  docker:
    image: docker:dind
    restart: always
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=
    volumes:
      - docker_data:/var/lib/docker
    ports:
      - "2375:2375"

  db:
    image: bitnami/mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=rootpassword
      - MARIADB_DATABASE=moodle
      - MARIADB_USER=moodle
      - MARIADB_PASSWORD=bitnami
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mariadb_data:/bitnami/mariadb
    depends_on:
      - docker

  moodle:
    image: docker.io/bitnamilegacy/moodle:4.5
    restart: always
    ports:
      - "8080:8080"
    environment:
      - MOODLE_DATABASE_HOST=db
      - MOODLE_DATABASE_USER=moodle
      - MOODLE_DATABASE_PASSWORD=bitnami
      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_SITE_URL=http://40.82.130.11:8080
      - ALLOW_EMPTY_PASSWORD=yes
      - PHP_MEMORY_LIMIT=512M
    volumes:
      - moodle_data:/bitnami/moodle
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
      - docker

volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  docker_data:
    driver: local
